// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03/07/2026, 14:50:00
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/emman/Documents/Codes/portfolio gd/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/Documents/Codes/portfolio gd/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/Documents/Codes/portfolio gd/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/Documents/Codes/portfolio gd/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/Documents/Codes/portfolio gd/plugins/**/*.{js,ts,mjs}","C:/Users/emman/Documents/Codes/portfolio gd/composables/**/*.{js,ts,mjs}","C:/Users/emman/Documents/Codes/portfolio gd/utils/**/*.{js,ts,mjs}","C:/Users/emman/Documents/Codes/portfolio gd/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/Documents/Codes/portfolio gd/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/emman/Documents/Codes/portfolio gd/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;